const express = require('express');
const bodyParser = require('body-parser');
const productRoutes = require('./routes/productRoutes');
const userRoutes = require('./routes/userRoutes');
const productCategoriesRoutes = require('./routes/productCategoriesRoutes');
const cartRoutes = require('./routes/cartRoutes');
const currentOrderRoutes = require('./routes/currentOrdersRoutes');
const cancelledOrderRoutes = require('./routes/cancelledOrdersRoutes');
const deliveredOrderRoutes = require('./routes/deliveredOrdersRoutes');
const wishlistRoutes = require('./routes/wishlistRoutes');
const orderRoutes = require('./routes/ordersRoutes');
const historyOrderRoutes = require('./routes/ordersHistoryRoutes');
const subscriptionRoutes = require('./routes/subscriptionRoutes');
const alternateAddressRoutes = require('./routes/alternateAddressRoutes');
const pausedSubcriptionRoutes = require('./routes/pausedSubscriptionRoutes');
const forgetpasswordRoutes = require('./routes/forgetPasswordRoutes');
const discountRoutes = require('./routes/discountroutes');
const invoiceRoutes = require('./routes/invoiceRoutes');
const feedbackRoutes = require('./routes/feedbackRoutes');
const activesubscriptionRoutes = require('./routes/activesubscriptionRoutes');
const cancelledscriptionRoutes = require('./routes/cancelledsubscriptionRoutes');
const allSubscriptionRoutes = require('./routes/AllsubscriptionRoutes');
const createInvoiceRoutes = require('./routes/createinvoiceRoutes');
const subscriptionOfUsersRoutes = require('./routes/subscriptionsofusersRoutes');
const reviewRoutes = require('./routes/reviewRoutes');
const refferalRoutes = require('./routes/refferalRoutes');
const returnJarRoutes = require('./routes/returnjarrequestRoutes');
const citiesRoutes = require('./routes/citiesRoutes');
const statesRoutes = require('./routes/statesRoutes');
const countriesRoutes = require('./routes/countriesRoutes');
require('dotenv').config();
const cors = require('cors');

 const app = express();
app.use(cors());

app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: true }));
app.use('/api/products', productRoutes);
app.use('/api/users', userRoutes);
app.use('/api/productcategories', productCategoriesRoutes);
app.use('/api/cart', cartRoutes);
app.use('/api/currentorders', currentOrderRoutes);
app.use('/api/cancelledorders', cancelledOrderRoutes);
app.use('/api/deliveredorders', deliveredOrderRoutes);
app.use('/api/wishlist', wishlistRoutes);
app.use('/api/orders', orderRoutes);
app.use('/api/ordershistory', historyOrderRoutes);
app.use('/api/subscription', subscriptionRoutes);
app.use('/api/alternateaddress', alternateAddressRoutes);
app.use('/api/pausedsubscription', pausedSubcriptionRoutes);
app.use('/api/forgetpassword', forgetpasswordRoutes);
app.use('/api/discount', discountRoutes);
app.use('/api/invoice', invoiceRoutes);
app.use('/api/feedback', feedbackRoutes);
app.use('/api/activesubscription', activesubscriptionRoutes);
app.use('/api/cancelledsubscription', cancelledscriptionRoutes);
app.use('/api/allsubscriptions', allSubscriptionRoutes);
app.use('/api/createinvoice', createInvoiceRoutes);
app.use('/api/subscriptionsofusers', subscriptionOfUsersRoutes);
app.use('/api/review', reviewRoutes);
app.use('/api/refferal', refferalRoutes);
app.use('/api/returnrequest', returnJarRoutes);
app.use('/api/cities', citiesRoutes);
app.use('/api/cities', statesRoutes);
app.use('/api/countries', countriesRoutes);

module.exports = app;
